# Use Debian-based Tomcat so apt-get works
FROM tomcat:9-jdk17-temurin-jammy


# Remove default ROOT app and add your WAR
RUN rm -rf /usr/local/tomcat/webapps/ROOT
COPY target/AdvancedCurrencyConverter.war /usr/local/tomcat/webapps/ROOT.war

# Copy wait-for-db script
COPY wait-for-db.sh /usr/local/bin/wait-for-db.sh
RUN chmod +x /usr/local/bin/wait-for-db.sh

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/wait-for-db.sh"]
CMD ["catalina.sh", "run"]
